### ISSUE TITLE
Fix or disable main branch FxIOS XCUITest failures

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#94] opened 2020-08-25 14:50 UTC
1. File issues for broken tests
2. Determine if quick fix or disable

**Comment by isabelrios** [comment] 2020-09-01 13:13
I have been looking at the failures.
There is one test (testLongPressReload) failing due to a real bug: https://github.com/mozilla-mobile/firefox-ios/issues/7248
The two related to the authentication prompt are failing locally too when running the tests, investigating if due to a real issue or change in implementation. Now the login screen is not locked when it should be according to the current implementation....

**Comment by isabelrios** [comment] 2020-09-01 13:35
For these two tests we need to modify them, removing the line: navigator.nowAt(SettingScreen) on L#49 and L#67. 
-testPromptPassCodeUponReentry
-testPromptPassCodeUponReentryWithDelay

Issue filed to track that work: https://github.com/mozilla-mobile/firefox-ios/issues/7249

**Comment by AaronMT** [comment] 2020-09-02 14:18
👍

**Comment by isabelrios** [comment] 2020-09-14 16:27
Those Authentication tests are fixed once [PR](https://github.com/mozilla-mobile/firefox-ios/pull/7250) landed. There has been a fix also for the Long tap on reload button to show Desktop/Mobile options.

We can move this issue to In Review to verify those tests and close it once we check them. If there are other ones failing, I would open a new issue for each one or related ones.

**Comment by isabelrios** [comment] 2020-09-15 09:04
There are two failures:
-one due to change that needs to be confirmed https://github.com/mozilla-mobile/firefox-ios/issues/7311
-intermittent on iPad: testSearchOption

I will go ahead and close this issue and open a new one to track the intermittent failure, testSearchOption on iPad.

**Closed as completed by isabelrios** 2020-09-15 09:04 UTC
